### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph-link-preview-expander#5]
@AlicjaSuska could you help with an icon for this extension?

**Comment by AlicjaSuska** [comment]
Sure thing!

**Comment by AlicjaSuska** [comment]
All done - please export from Figma:

https://www.figma.com/file/LZMNKvNDwaPKrdscrGTTNH/Link-preview-extension-icon-5?node-id=1%3A35

**Comment by AlicjaSuska** [comment]
@felixfbecker when are you planning to add this icon to the extension?

**Comment by AlicjaSuska** [comment]
@tjkandala since you've written the extension - when are you planning to add this icon?
